# Generated by Django 6.0.4 on 2026-04-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="link",
            field=models.URLField(default="http://example.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.CharField(default="Not rated", max_length=20),
            preserve_default=False,
        ),
    ]
