# Generated by Django 6.0.4 on 2026-04-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_link_book_price_book_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
