# Generated by Django 6.0.4 on 2026-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
