# Generated by Django 6.0.4 on 2026-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="recommendation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
